version: "3.6"
services:
  input-api:
    build:
      context: .
    ports:
      - "8080:8080"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
    logging:
      driver: none
